# Generated by Django 2.0.2 on 2018-11-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20181111_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-pub_date']},
        ),
    ]
