# Generated by Django 2.0.2 on 2018-11-12 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20181112_0119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': None},
        ),
    ]
