# Generated by Django 2.0.2 on 2018-11-12 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20181112_0121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-pub_date']},
        ),
    ]
