# Generated by Django 2.0.2 on 2018-11-12 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_auto_20181112_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['pub_date']},
        ),
    ]
